spring:
  application:
    name: ProjectAI

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:9010/pgvector-test?sslmode=disable&options=-c%20timezone=UTC}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          time_zone: UTC

  ai:
    google:
      genai:
        api-key: ${API_KEY:demo-gemini-key}
        chat:
          options:
            model: gemini-3.6-flash
        embedding:
          api-key: ${API_KEY:demo-gemini-key}
          text:
            dimensions: 768
    vectorstore:
      pgvector:
        dimensions: 768
        initialize-schema: true


jwt:
  secret-key: habjehbdkabhiwhlknaleiaahu3hiajfefnjsnljeioeokrjwu

stripe:
  api:
    secret: ${STRIPE_SECRET:sk_test_placeholder}
  webhook:
    secret: ${WEBHOOK_SECRET:whsec_placeholder}

client.url: http://localhost:3000

logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG

minio:
  url: http://127.0.0.1:9000
  access-key: avanish
  secret-key: avanish7080
  project-bucket: project-ai-basket